
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author COPECO -13
 */
public class Principal extends javax.swing.JFrame {
    DefaultMutableTreeNode nodoSeleccionado;
    String jugadorSeleccionado;
    Villanos tVillanos;
    Heroes tHeroes;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_heroes = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtHeroeNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinHeroeFuerza = new javax.swing.JSpinner();
        spinHeroeAfisica = new javax.swing.JSpinner();
        spinHeroeAmental = new javax.swing.JSpinner();
        btAgregarHeroe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlHeroes = new javax.swing.JList<>();
        bHeroeModificar = new javax.swing.JButton();
        btnHeroeModificar = new javax.swing.JButton();
        bHeroeEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtHeroePoder = new javax.swing.JTextField();
        txtHeroeDebilidad = new javax.swing.JTextField();
        jd_villanos = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtVillanoNombre = new javax.swing.JTextField();
        spinVillanoFuerza = new javax.swing.JSpinner();
        spinVillanoAfisica = new javax.swing.JSpinner();
        spinVillanoAmental = new javax.swing.JSpinner();
        btAgregarVillano = new javax.swing.JButton();
        bVillanoModificar = new javax.swing.JButton();
        btnVillanoModificar = new javax.swing.JButton();
        bVillanoEliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlVillanos = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        txtVillanoPoder = new javax.swing.JTextField();
        txtVillanoDebilidad = new javax.swing.JTextField();
        jd_escuadronH = new javax.swing.JDialog();
        jd_escuadronV = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmHeroe = new javax.swing.JMenuItem();
        jmVillano = new javax.swing.JMenuItem();
        jmEscuadrones = new javax.swing.JMenu();
        jmEscVillanos = new javax.swing.JMenuItem();
        jmEscHeroe = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Nombre:");

        jLabel4.setText("Poder:");

        jLabel5.setText("Debilidad:");

        jLabel6.setText("Fuerza:");

        jLabel7.setText("Agilidad Fisica:");

        jLabel8.setText("Agilidad Mental:");

        btAgregarHeroe.setText("Agregar");
        btAgregarHeroe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarHeroeMouseClicked(evt);
            }
        });

        jlHeroes.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jlHeroes);

        bHeroeModificar.setText("Obtener valores");
        bHeroeModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHeroeModificarMouseClicked(evt);
            }
        });

        btnHeroeModificar.setText("Modificar");
        btnHeroeModificar.setEnabled(false);
        btnHeroeModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHeroeModificarMouseClicked(evt);
            }
        });

        bHeroeEliminar.setText("Eliminar");
        bHeroeEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHeroeEliminarMouseClicked(evt);
            }
        });

        jLabel2.setText("Heroes");

        javax.swing.GroupLayout jd_heroesLayout = new javax.swing.GroupLayout(jd_heroes.getContentPane());
        jd_heroes.getContentPane().setLayout(jd_heroesLayout);
        jd_heroesLayout.setHorizontalGroup(
            jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_heroesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jd_heroesLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_heroesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bHeroeModificar)
                .addGap(18, 18, 18)
                .addComponent(btnHeroeModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bHeroeEliminar)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_heroesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHeroeNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(spinHeroeFuerza)
                    .addComponent(spinHeroeAfisica)
                    .addComponent(spinHeroeAmental)
                    .addComponent(txtHeroePoder)
                    .addComponent(txtHeroeDebilidad))
                .addGap(52, 52, 52)
                .addComponent(btAgregarHeroe)
                .addGap(29, 29, 29))
        );
        jd_heroesLayout.setVerticalGroup(
            jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_heroesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeroeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHeroePoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHeroeDebilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinHeroeFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinHeroeAfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spinHeroeAmental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarHeroe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHeroeModificar)
                    .addComponent(btnHeroeModificar)
                    .addComponent(bHeroeEliminar))
                .addGap(24, 24, 24))
        );

        jLabel3.setText("Nombre:");

        jLabel9.setText("Poder:");

        jLabel10.setText("Debilidad:");

        jLabel11.setText("Fuerza:");

        jLabel12.setText("Agilidad Fisica:");

        jLabel13.setText("Agilidad Mental:");

        btAgregarVillano.setText("Agregar");
        btAgregarVillano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarVillanoMouseClicked(evt);
            }
        });
        btAgregarVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarVillanoActionPerformed(evt);
            }
        });

        bVillanoModificar.setText("Obtener valores");
        bVillanoModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bVillanoModificarMouseClicked(evt);
            }
        });

        btnVillanoModificar.setText("Modificar");
        btnVillanoModificar.setEnabled(false);
        btnVillanoModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVillanoModificarMouseClicked(evt);
            }
        });

        bVillanoEliminar.setText("Eliminar");
        bVillanoEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bVillanoEliminarMouseClicked(evt);
            }
        });

        jlVillanos.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jlVillanos);

        jLabel16.setText("Villano");

        javax.swing.GroupLayout jd_villanosLayout = new javax.swing.GroupLayout(jd_villanos.getContentPane());
        jd_villanos.getContentPane().setLayout(jd_villanosLayout);
        jd_villanosLayout.setHorizontalGroup(
            jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_villanosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jd_villanosLayout.createSequentialGroup()
                        .addComponent(bVillanoModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVillanoModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bVillanoEliminar)))
                .addContainerGap())
            .addGroup(jd_villanosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVillanoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(spinVillanoFuerza)
                    .addComponent(spinVillanoAfisica)
                    .addComponent(spinVillanoAmental)
                    .addComponent(txtVillanoPoder, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtVillanoDebilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(btAgregarVillano)
                .addGap(19, 19, 19))
            .addGroup(jd_villanosLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_villanosLayout.setVerticalGroup(
            jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_villanosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_villanosLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinVillanoFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinVillanoAfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinVillanoAmental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(btAgregarVillano)))
                    .addGroup(jd_villanosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVillanoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtVillanoPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtVillanoDebilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_villanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVillanoModificar)
                    .addComponent(btnVillanoModificar)
                    .addComponent(bVillanoEliminar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jd_escuadronHLayout = new javax.swing.GroupLayout(jd_escuadronH.getContentPane());
        jd_escuadronH.getContentPane().setLayout(jd_escuadronHLayout);
        jd_escuadronHLayout.setHorizontalGroup(
            jd_escuadronHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_escuadronHLayout.setVerticalGroup(
            jd_escuadronHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_escuadronVLayout = new javax.swing.GroupLayout(jd_escuadronV.getContentPane());
        jd_escuadronV.getContentPane().setLayout(jd_escuadronVLayout);
        jd_escuadronVLayout.setHorizontalGroup(
            jd_escuadronVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_escuadronVLayout.setVerticalGroup(
            jd_escuadronVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        jMenu1.setText("Squad");

        jmHeroe.setText("Heroe");
        jmHeroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHeroeActionPerformed(evt);
            }
        });
        jMenu1.add(jmHeroe);

        jmVillano.setText("Villano");
        jmVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVillanoActionPerformed(evt);
            }
        });
        jMenu1.add(jmVillano);

        jmEscuadrones.setText("Escuadrones");

        jmEscVillanos.setText("Escuadrones Villanos");
        jmEscVillanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEscVillanosActionPerformed(evt);
            }
        });
        jmEscuadrones.add(jmEscVillanos);

        jmEscHeroe.setText("Escuadrones Heroes");
        jmEscHeroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEscHeroeActionPerformed(evt);
            }
        });
        jmEscuadrones.add(jmEscHeroe);

        jMenu1.add(jmEscuadrones);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmHeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHeroeActionPerformed
        // TODO add your handling code here:
        jd_heroes.setModal(true);
        jd_heroes.setLocationRelativeTo(this);
        jd_heroes.pack();
        jd_heroes.setResizable(false);
        jd_heroes.setVisible(true);
    }//GEN-LAST:event_jmHeroeActionPerformed

    private void jmVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVillanoActionPerformed
        // TODO add your handling code here:
        jd_villanos.setModal(true);
        jd_villanos.setLocationRelativeTo(this);
        jd_villanos.pack();
        jd_villanos.setResizable(false);
        jd_villanos.setVisible(true);
    }//GEN-LAST:event_jmVillanoActionPerformed

    private void jmEscVillanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEscVillanosActionPerformed
        // TODO add your handling code here:
        jd_escuadronV.setModal(true);
        jd_escuadronV.setLocationRelativeTo(this);
        jd_escuadronV.pack();
        jd_escuadronV.setResizable(false);
        jd_escuadronV.setVisible(true);
    }//GEN-LAST:event_jmEscVillanosActionPerformed

    private void jmEscHeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEscHeroeActionPerformed
        // TODO add your handling code here:
        jd_escuadronH.setModal(true);
        jd_escuadronH.setLocationRelativeTo(this);
        jd_escuadronH.pack();
        jd_escuadronH.setResizable(false);
        jd_escuadronH.setVisible(true);
    }//GEN-LAST:event_jmEscHeroeActionPerformed

    private void bHeroeModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHeroeModificarMouseClicked
        // MODIFICAR HEROE
        try {
            DefaultListModel modelo = (DefaultListModel) jlHeroes.getModel();
            jlHeroes.setEnabled(false);
            if (jlHeroes.getSelectedIndex() != -1){
                btnHeroeModificar.setEnabled(true);
                bHeroeModificar.setEnabled(false);
                bHeroeEliminar.setEnabled(false);
                btAgregarHeroe.setEnabled(false);
                Heroes heroes = (Heroes) modelo.getElementAt(jlHeroes.getSelectedIndex());
                tHeroes = heroes;
                txtHeroeNombre.setText(heroes.getNombre());
                txtHeroePoder.setText(heroes.getPoder());
                txtHeroeDebilidad.setText(heroes.getDebilidad());
                
                spinHeroeFuerza.setValue(heroes.getFuerza());
                spinHeroeAfisica.setValue(heroes.getAgilidadFisica());
                spinHeroeAmental.setValue(heroes.getAgilidadMental());
            } else {
                JOptionPane.showMessageDialog(jd_heroes, "Error al obtener equipos!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_heroes, "Error!\n" + e.getMessage());
        }
    }//GEN-LAST:event_bHeroeModificarMouseClicked

    private void btnHeroeModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHeroeModificarMouseClicked
        try {
            DefaultListModel modelo = (DefaultListModel) jlHeroes.getModel();
            if (jlHeroes.getSelectedIndex() != -1) {
                String nombre = txtHeroeNombre.getText();
                String poder = txtHeroePoder.getText();
                String debilidad = txtHeroeDebilidad.getText();

                int fuerza = (Integer) spinHeroeFuerza.getValue();
                int agilidadFisica = (Integer) spinHeroeAfisica.getValue();
                int agilidadMental = (Integer) spinHeroeAmental.getValue();
                String posicion = "";
                
                boolean error = false;
                if (fuerza < 0 || fuerza > 100) {
                    error = true;
                }
                if (agilidadFisica < 0 || agilidadFisica > 100) {
                    error = true;
                }
                if (agilidadMental < 0 || agilidadMental > 100) {
                    error = true;
            }
                
                if (!error) {
                    tHeroes.setNombre(nombre);
                    tHeroes.setPoder(poder);
                    tHeroes.setDebilidad(debilidad);
                    tHeroes.setFuerza(fuerza);
                    tHeroes.setAgilidadFisica(agilidadFisica);
                    tHeroes.setAgilidadMental(agilidadMental);
                    modelo.set(jlHeroes.getSelectedIndex(), tHeroes);
                    jlHeroes.setEnabled(true);
                    bHeroeModificar.setEnabled(true);
                    btnHeroeModificar.setEnabled(false);
                    bHeroeEliminar.setEnabled(true);
                    btAgregarHeroe.setEnabled(true);
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(jd_villanos, "Error!\n" + e.getMessage());
        } 
    }//GEN-LAST:event_btnHeroeModificarMouseClicked

    private void bHeroeEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHeroeEliminarMouseClicked
        try {
            DefaultListModel modelo = (DefaultListModel) jlHeroes.getModel();
            if (jlHeroes.getSelectedIndex() != -1){
                modelo.remove(jlHeroes.getSelectedIndex());
                // Modificar
            }else
                JOptionPane.showMessageDialog(jd_heroes, "Error al eliminar!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_heroes, "Error!\n" + e.getMessage());
        }
    }//GEN-LAST:event_bHeroeEliminarMouseClicked

    private void bVillanoModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVillanoModificarMouseClicked
        // TODO add your handling code here:
         // MODIFICAR VILLANO:
        try {
            DefaultListModel modelo = (DefaultListModel) jlVillanos.getModel();
            jlVillanos.setEnabled(false);
            if (jlVillanos.getSelectedIndex() != -1){
                btnVillanoModificar.setEnabled(true);
                bVillanoModificar.setEnabled(false);
                bVillanoEliminar.setEnabled(false);
                btAgregarVillano.setEnabled(false);
                Villanos villanos = (Villanos) modelo.getElementAt(jlVillanos.getSelectedIndex());
                tVillanos = villanos;
                txtVillanoNombre.setText(villanos.getNombre());
                txtVillanoPoder.setText(villanos.getPoder());
                txtVillanoDebilidad.setText(villanos.getDebilidad());
                
                spinVillanoFuerza.setValue(villanos.getFuerza());
                spinVillanoAfisica.setValue(villanos.getAgilidadFisica());
                spinVillanoAmental.setValue(villanos.getAgilidadMental());
            } else {
                JOptionPane.showMessageDialog(jd_villanos, "Error al obtener equipos!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_villanos, "Error!\n" + e.getMessage());
        }
    }//GEN-LAST:event_bVillanoModificarMouseClicked

    private void btnVillanoModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVillanoModificarMouseClicked
        // TODO add your handling code here:
        try {
            DefaultListModel modelo = (DefaultListModel) jlVillanos.getModel();
            if (jlVillanos.getSelectedIndex() != -1) {
                String nombre = txtVillanoNombre.getText();
                String poder = txtVillanoPoder.getText();
                String debilidad = txtVillanoDebilidad.getText();

                int fuerza = (Integer) spinVillanoFuerza.getValue();
                int agilidadFisica = (Integer) spinVillanoAfisica.getValue();
                int agilidadMental = (Integer) spinVillanoAmental.getValue();
                String posicion = "";
                
                boolean error = false;
                if (fuerza < 0 || fuerza > 100) {
                    error = true;
                }
                if (agilidadFisica < 0 || agilidadFisica > 100) {
                    error = true;
                }
                if (agilidadMental < 0 || agilidadMental > 100) {
                    error = true;
            }
                
                if (!error) {
                    tVillanos.setNombre(nombre);
                    tVillanos.setPoder(poder);
                    tVillanos.setDebilidad(debilidad);
                    tVillanos.setFuerza(fuerza);
                    tVillanos.setAgilidadFisica(agilidadFisica);
                    tVillanos.setAgilidadMental(agilidadMental);
                    modelo.set(jlVillanos.getSelectedIndex(), tVillanos);
                    jlVillanos.setEnabled(true);
                    bVillanoModificar.setEnabled(true);
                    btnVillanoModificar.setEnabled(false);
                    bVillanoEliminar.setEnabled(true);
                    btAgregarVillano.setEnabled(true);
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(jd_villanos, "Error!\n" + e.getMessage());
        } 
        
    }//GEN-LAST:event_btnVillanoModificarMouseClicked

    private void bVillanoEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVillanoEliminarMouseClicked
        // TODO add your handling code here:
         // ELIMINAR VILLANOS
        try {
            DefaultListModel modelo = (DefaultListModel) jlVillanos.getModel();
            if (jlVillanos.getSelectedIndex() != -1){
                modelo.remove(jlVillanos.getSelectedIndex());
                // Modificar
            }else
                JOptionPane.showMessageDialog(jd_villanos, "Error al eliminar!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_villanos, "Error!\n" + e.getMessage());
        }
    }//GEN-LAST:event_bVillanoEliminarMouseClicked

    private void btAgregarVillanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarVillanoMouseClicked
        // TODO add your handling code here:
        // AGREGAR VILLANO
        try {
            boolean error = false;
            String nombre = txtVillanoNombre.getText();
            String poder = txtVillanoPoder.getText();
            String debilidad = txtVillanoDebilidad.getText();

            int fuerza = (Integer) spinVillanoFuerza.getValue();
            int agilidadFisica = (Integer) spinVillanoAfisica.getValue();
            int agilidadMental = (Integer) spinVillanoAmental.getValue();
            String posicion = "";

            if (fuerza < 0 || fuerza > 100) {
                error = true;
            }
            if (agilidadFisica < 0 || agilidadFisica > 100) {
                error = true;
            }
            if (agilidadMental < 0 || agilidadMental > 100) {
                error = true;
            }

            if (!error) {
                ArrayList<EscuadronVillano> baseEscuadron = null;
                
                Villanos v = new Villanos(nombre, poder, debilidad, baseEscuadron , fuerza, agilidadFisica, agilidadMental);
                DefaultListModel modelo = (DefaultListModel) jlVillanos.getModel();
                modelo.addElement(v);
            } else {
                JOptionPane.showMessageDialog(jlVillanos, "Error al ingresar jugadores!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jlVillanos, "Error!\n" + e.getMessage());
        }

    }//GEN-LAST:event_btAgregarVillanoMouseClicked

    private void btAgregarVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarVillanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarVillanoActionPerformed

    private void btAgregarHeroeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarHeroeMouseClicked
        // TODO add your handling code here:
        try {
            boolean error = false;
            String nombre = txtHeroeNombre.getText();
            String poder = txtHeroePoder.getText();
            String debilidad = txtHeroeDebilidad.getText();

            int fuerza = (Integer) spinHeroeFuerza.getValue();
            int agilidadFisica = (Integer) spinHeroeAfisica.getValue();
            int agilidadMental = (Integer) spinHeroeAmental.getValue();
            String posicion = "";

            if (fuerza < 0 || fuerza > 100) {
                error = true;
            }
            if (agilidadFisica < 0 || agilidadFisica > 100) {
                error = true;
            }
            if (agilidadMental < 0 || agilidadMental > 100) {
                error = true;
            }

            if (!error) {
                ArrayList<EscuadronVillano> baseEscuadron = null;
                ArrayList<EscuadronHeroe> baseEscuadronH = null;
                
                Heroes h = new Heroes(nombre, poder, debilidad, baseEscuadronH, fuerza, agilidadFisica, agilidadMental);
                DefaultListModel modelo = (DefaultListModel) jlHeroes.getModel();
                modelo.addElement(h);
            } else {
                JOptionPane.showMessageDialog(jlHeroes, "Error al ingresar jugadores!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jlHeroes, "Error!\n" + e.getMessage());
        }
    }//GEN-LAST:event_btAgregarHeroeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHeroeEliminar;
    private javax.swing.JButton bHeroeModificar;
    private javax.swing.JButton bVillanoEliminar;
    private javax.swing.JButton bVillanoModificar;
    private javax.swing.JButton btAgregarHeroe;
    private javax.swing.JButton btAgregarVillano;
    private javax.swing.JButton btnHeroeModificar;
    private javax.swing.JButton btnVillanoModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JDialog jd_escuadronH;
    private javax.swing.JDialog jd_escuadronV;
    private javax.swing.JDialog jd_heroes;
    private javax.swing.JDialog jd_villanos;
    private javax.swing.JList<String> jlHeroes;
    private javax.swing.JList<String> jlVillanos;
    private javax.swing.JMenuItem jmEscHeroe;
    private javax.swing.JMenuItem jmEscVillanos;
    private javax.swing.JMenu jmEscuadrones;
    private javax.swing.JMenuItem jmHeroe;
    private javax.swing.JMenuItem jmVillano;
    private javax.swing.JSpinner spinHeroeAfisica;
    private javax.swing.JSpinner spinHeroeAmental;
    private javax.swing.JSpinner spinHeroeFuerza;
    private javax.swing.JSpinner spinVillanoAfisica;
    private javax.swing.JSpinner spinVillanoAmental;
    private javax.swing.JSpinner spinVillanoFuerza;
    private javax.swing.JTextField txtHeroeDebilidad;
    private javax.swing.JTextField txtHeroeNombre;
    private javax.swing.JTextField txtHeroePoder;
    private javax.swing.JTextField txtVillanoDebilidad;
    private javax.swing.JTextField txtVillanoNombre;
    private javax.swing.JTextField txtVillanoPoder;
    // End of variables declaration//GEN-END:variables
}
